import Head from 'next/head';
import Navbar2 from '../../components/navbar2';
import Link from 'next/link';
import { useState } from 'react';

export default function addCap() {
  const [capName, setCapName] = useState('');
  const [capFiles, setCapFiles] = useState('');
  const [capTime, setCapTime] = useState('');
  const [capDate, setCapDate] = useState('');

  var date = new Date().getDate(); //To get the Current Date
  var month = new Date().getMonth() + 1; //To get the Current Month
  var year = new Date().getFullYear(); //To get the Current Year
  var hours = new Date().getHours(); //To get the Current Hours
  var min = new Date().getMinutes(); //To get the Current Minutes

  console.log({
    date,
    month,
    year,
    hours,
    min,
  });

  const handSubmit = (e) => {
    e.preventDefault();

    const addCap = {
      capName,
      capFiles,
      capTime,
      capDate,
    };
    console.log(addCap);
  };

  return (
    <>
      <Head>
        <title>Add Capsule</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Navbar2 />

      <div className='dark:bg-gray-900 h-screen'>
        <div className='flex flex-col items-center pt-8 mx-auto'>
          <div className='rounded-xl dark:bg-gray-800'>
            <div className='p-6 md:space-y-6 sm:p-8'>
              <h1 className='font-bold text-gray-900 text-2xl text-white'>
                Add Capsule
              </h1>
              <form className='space-y-4 md:space-y-6' action='#'>
                <div>
                  <h1 className='mb-2 text-lg text-white'>Capsule Name</h1>
                  <input
                    type='text'
                    name='capsuleName'
                    className=' sm:text-sm rounded-lg w-full p-2.5 bg-gray-700 border-gray-600 text-white'
                    required=''
                    onChange={(e) => setCapName(e.target.value)}
                  />
                </div>
                <div>
                  <label className='block mb-2 text-lg text-gray-900 dark:text-white'>
                    Add Capsule Input (Files)
                  </label>
                  <input
                    type='file'
                    className='sm:text-sm rounded-lg w-full p-2.5 dark:bg-gray-700 text-white'
                    required=''
                  />
                </div>
                <div>
                  <h1 className='mb-2 text-lg text-white'>
                    Capsule Time And Date
                  </h1>
                  <input
                    type='time'
                    name='capsuleTime'
                    className='sm:text-sm rounded-lg p-2.5 bg-gray-700 text-white'
                    required=''
                    onChange={() => setCapTime()}
                  />
                  <input
                    type='date'
                    name='capsuleTime'
                    className='sm:text-sm rounded-lg p-2.5 dark:bg-gray-700 text-white ml-2'
                    required=''
                    onChange={() => setCapDate()}
                  />
                </div>
                <div className='flex items-center'>
                  <input type='checkbox' />
                  <p className='dark:text-red-500 ml-2'>
                    I agree that files will be locked and inaccessable
                  </p>
                </div>
                <div className='flex justify-center'>
                  <button
                    type='submit'
                    className='w-2/5 text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 mr-5'
                    onClick={handSubmit}
                  >
                    Add Capsule
                  </button>
                  <div className='w-2/5 text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700'>
                    <Link href='./main'>
                      <button type='submit'>Cancel</button>
                    </Link>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
