import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Capsulate</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main>
        <section className='bg-gray-50 dark:bg-gray-900'>
          <div class='text-white h-screen'>
            <div className=' justify-center h-screen flex items-center text-2xl'>
              <h1 className='me-2'>What would you like to do?</h1>
              <Link href='./register'>
                <button className='mr-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-2xl px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800'>
                  Register
                </button>
              </Link>
              <Link href='./login'>
                <button className='mr-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-2xl px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 '>
                  Login
                </button>
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
