import Head from 'next/head';
import Navbar2 from '../../components/navbar2';

const Capsule = (
  <div className='grid justify-items-center pt-10 text-white'>
    <div className='bg-gray-700 border-2 py-2 text-xl flex justify-center rounded-lg'>
      <div className='ml-2 border-2 p-3 rounded-lg bg-green-700'>
        <h1>Name of Capsule</h1>
      </div>
      <div className='ml-2 border-2 px-10 flex items-center bg-red-700 rounded-lg'>
        <h1>Timer:</h1>
        <h2 className='ml-2'>Timer Number</h2>
      </div>
      <div className='ml-2 mr-2 border-2 text-white bg-blue-700 font-medium rounded-lg p-3'>
        <h1>Number Of Files</h1>
      </div>
    </div>
  </div>
);

export default function Main() {
  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Navbar2 />
      <div className='h-screen dark:bg-gray-900'>
        {Capsule}
        {Capsule}
        {Capsule}
      </div>
    </>
  );
}
